receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  tail_sampling:
    decision_wait: 5s
    policies: [{
      name: dont-sample-healthcheck,
      type: and,
      and:
        {
          and_sub_policy:
            [
              {
                name: route-live-ready-policy,
                type: string_attribute,
                string_attribute:
                  {
                    key: http.route,
                    values: ["/.well-known/health"],
                    invert_match: true,
                  },
              },
              {
                name: probabilistic-policy,
                type: probabilistic,
                probabilistic: { sampling_percentage: 100 },
              },
            ],
        },
      }]


exporters:
  otlp:
    endpoint: http://jaeger:4317
    tls:
      insecure: true
  debug:
    verbosity: basic #detailed

extensions:
  health_check:
    path: "/.well-known/health"
    endpoint: "0.0.0.0:13133"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling,batch]
      exporters: [otlp,debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,debug]

