name: Loadtest

on:
  push:
    branches: ["master"]
  pull_request:

defaults:
  run:
    working-directory: test/load

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: clippy

      - name: Lint
        run: RUSTFLAGS="-Dwarnings" cargo clippy --all-targets --all-features

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: rustfmt

      - name: Format
        run: cargo fmt --all -- --check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.78.0

      - name: Build
        run: cargo build

  supply:
    name: Supply Chain Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.78.0

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked

      - name: Scan
        run: cargo audit --ignore RUSTSEC-2023-0005 --ignore RUSTSEC-2024-0019 --ignore RUSTSEC-2023-0065 --ignore RUSTSEC-2023-0001 --ignore RUSTSEC-2021-0127 --ignore RUSTSEC-2024-0357
