name: Security

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  security:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Trufflehog Scan
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified

    - name: OWASP ZAP
      steps:
      uses: zaproxy/action-baseline@v0.12.0
      with:
        target: 'http://local.martletplace.ca'
        allow_issue_writing: false
        fail_action: true